// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/osai/reporting/v1/reporting.proto

package reportingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_osai_reporting_v1_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type Balance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId  string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	Currency       string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	AvailableMinor int64                  `protobuf:"varint,3,opt,name=available_minor,json=availableMinor,proto3" json:"available_minor,omitempty"`
	HeldMinor      int64                  `protobuf:"varint,4,opt,name=held_minor,json=heldMinor,proto3" json:"held_minor,omitempty"`
	ReservedMinor  int64                  `protobuf:"varint,5,opt,name=reserved_minor,json=reservedMinor,proto3" json:"reserved_minor,omitempty"`
	TotalMinor     int64                  `protobuf:"varint,6,opt,name=total_minor,json=totalMinor,proto3" json:"total_minor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_proto_osai_reporting_v1_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *Balance) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *Balance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Balance) GetAvailableMinor() int64 {
	if x != nil {
		return x.AvailableMinor
	}
	return 0
}

func (x *Balance) GetHeldMinor() int64 {
	if x != nil {
		return x.HeldMinor
	}
	return 0
}

func (x *Balance) GetReservedMinor() int64 {
	if x != nil {
		return x.ReservedMinor
	}
	return 0
}

func (x *Balance) GetTotalMinor() int64 {
	if x != nil {
		return x.TotalMinor
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	InstitutionId string                 `protobuf:"bytes,2,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	CorrelationId string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TradeId       string                 `protobuf:"bytes,9,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	SettlementId  string                 `protobuf:"bytes,10,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_osai_reporting_v1_reporting_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Transaction) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Transaction) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Transaction) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

type GetBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesRequest) Reset() {
	*x = GetBalancesRequest{}
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesRequest) ProtoMessage() {}

func (x *GetBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetBalancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_reporting_v1_reporting_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalancesRequest) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

type GetBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*Balance             `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesResponse) Reset() {
	*x = GetBalancesResponse{}
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesResponse) ProtoMessage() {}

func (x *GetBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetBalancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_osai_reporting_v1_reporting_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalancesResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_reporting_v1_reporting_proto_rawDescGZIP(), []int{5}
}

func (x *ListTransactionsRequest) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *ListTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTransactionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListTransactionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*Transaction         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page           int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total          int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	NextCursor     string                 `protobuf:"bytes,5,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	PreviousCursor string                 `protobuf:"bytes,6,opt,name=previous_cursor,json=previousCursor,proto3" json:"previous_cursor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_reporting_v1_reporting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_osai_reporting_v1_reporting_proto_rawDescGZIP(), []int{6}
}

func (x *ListTransactionsResponse) GetItems() []*Transaction {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListTransactionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTransactionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListTransactionsResponse) GetPreviousCursor() string {
	if x != nil {
		return x.PreviousCursor
	}
	return ""
}

var File_proto_osai_reporting_v1_reporting_proto protoreflect.FileDescriptor

const file_proto_osai_reporting_v1_reporting_proto_rawDesc = "" +
	"\n" +
	"'proto/osai/reporting/v1/reporting.proto\x12\x11osai.reporting.v1\"U\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\xdc\x01\n" +
	"\aBalance\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12'\n" +
	"\x0favailable_minor\x18\x03 \x01(\x03R\x0eavailableMinor\x12\x1d\n" +
	"\n" +
	"held_minor\x18\x04 \x01(\x03R\theldMinor\x12%\n" +
	"\x0ereserved_minor\x18\x05 \x01(\x03R\rreservedMinor\x12\x1f\n" +
	"\vtotal_minor\x18\x06 \x01(\x03R\n" +
	"totalMinor\"\xce\x02\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12%\n" +
	"\x0einstitution_id\x18\x02 \x01(\tR\rinstitutionId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\voccurred_at\x18\a \x01(\tR\n" +
	"occurredAt\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrade_id\x18\t \x01(\tR\atradeId\x12#\n" +
	"\rsettlement_id\x18\n" +
	" \x01(\tR\fsettlementId\";\n" +
	"\x12GetBalancesRequest\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\"M\n" +
	"\x13GetBalancesResponse\x126\n" +
	"\bbalances\x18\x01 \x03(\v2\x1a.osai.reporting.v1.BalanceR\bbalances\"\x89\x01\n" +
	"\x17ListTransactionsRequest\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"\xe1\x01\n" +
	"\x18ListTransactionsResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.osai.reporting.v1.TransactionR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1f\n" +
	"\vnext_cursor\x18\x05 \x01(\tR\n" +
	"nextCursor\x12'\n" +
	"\x0fprevious_cursor\x18\x06 \x01(\tR\x0epreviousCursor2\xdd\x01\n" +
	"\x10ReportingService\x12\\\n" +
	"\vGetBalances\x12%.osai.reporting.v1.GetBalancesRequest\x1a&.osai.reporting.v1.GetBalancesResponse\x12k\n" +
	"\x10ListTransactions\x12*.osai.reporting.v1.ListTransactionsRequest\x1a+.osai.reporting.v1.ListTransactionsResponseB:Z8github.com/osai/osai/proto/osai/reporting/v1;reportingv1b\x06proto3"

var (
	file_proto_osai_reporting_v1_reporting_proto_rawDescOnce sync.Once
	file_proto_osai_reporting_v1_reporting_proto_rawDescData []byte
)

func file_proto_osai_reporting_v1_reporting_proto_rawDescGZIP() []byte {
	file_proto_osai_reporting_v1_reporting_proto_rawDescOnce.Do(func() {
		file_proto_osai_reporting_v1_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_osai_reporting_v1_reporting_proto_rawDesc), len(file_proto_osai_reporting_v1_reporting_proto_rawDesc)))
	})
	return file_proto_osai_reporting_v1_reporting_proto_rawDescData
}

var file_proto_osai_reporting_v1_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_osai_reporting_v1_reporting_proto_goTypes = []any{
	(*Pagination)(nil),               // 0: osai.reporting.v1.Pagination
	(*Balance)(nil),                  // 1: osai.reporting.v1.Balance
	(*Transaction)(nil),              // 2: osai.reporting.v1.Transaction
	(*GetBalancesRequest)(nil),       // 3: osai.reporting.v1.GetBalancesRequest
	(*GetBalancesResponse)(nil),      // 4: osai.reporting.v1.GetBalancesResponse
	(*ListTransactionsRequest)(nil),  // 5: osai.reporting.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil), // 6: osai.reporting.v1.ListTransactionsResponse
}
var file_proto_osai_reporting_v1_reporting_proto_depIdxs = []int32{
	1, // 0: osai.reporting.v1.GetBalancesResponse.balances:type_name -> osai.reporting.v1.Balance
	2, // 1: osai.reporting.v1.ListTransactionsResponse.items:type_name -> osai.reporting.v1.Transaction
	3, // 2: osai.reporting.v1.ReportingService.GetBalances:input_type -> osai.reporting.v1.GetBalancesRequest
	5, // 3: osai.reporting.v1.ReportingService.ListTransactions:input_type -> osai.reporting.v1.ListTransactionsRequest
	4, // 4: osai.reporting.v1.ReportingService.GetBalances:output_type -> osai.reporting.v1.GetBalancesResponse
	6, // 5: osai.reporting.v1.ReportingService.ListTransactions:output_type -> osai.reporting.v1.ListTransactionsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_osai_reporting_v1_reporting_proto_init() }
func file_proto_osai_reporting_v1_reporting_proto_init() {
	if File_proto_osai_reporting_v1_reporting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_osai_reporting_v1_reporting_proto_rawDesc), len(file_proto_osai_reporting_v1_reporting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_osai_reporting_v1_reporting_proto_goTypes,
		DependencyIndexes: file_proto_osai_reporting_v1_reporting_proto_depIdxs,
		MessageInfos:      file_proto_osai_reporting_v1_reporting_proto_msgTypes,
	}.Build()
	File_proto_osai_reporting_v1_reporting_proto = out.File
	file_proto_osai_reporting_v1_reporting_proto_goTypes = nil
	file_proto_osai_reporting_v1_reporting_proto_depIdxs = nil
}
