// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/osai/quote/v1/quote.proto

package quotev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMinor   int64                  `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_osai_quote_v1_quote_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateQuoteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId   string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	BaseAmountMinor int64                  `protobuf:"varint,4,opt,name=base_amount_minor,json=baseAmountMinor,proto3" json:"base_amount_minor,omitempty"`
	BaseCurrency    string                 `protobuf:"bytes,5,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency   string                 `protobuf:"bytes,6,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	DestinationRail string                 `protobuf:"bytes,7,opt,name=destination_rail,json=destinationRail,proto3" json:"destination_rail,omitempty"`
	Urgency         string                 `protobuf:"bytes,8,opt,name=urgency,proto3" json:"urgency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateQuoteRequest) Reset() {
	*x = CreateQuoteRequest{}
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuoteRequest) ProtoMessage() {}

func (x *CreateQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuoteRequest.ProtoReflect.Descriptor instead.
func (*CreateQuoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_quote_v1_quote_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQuoteRequest) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *CreateQuoteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateQuoteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateQuoteRequest) GetBaseAmountMinor() int64 {
	if x != nil {
		return x.BaseAmountMinor
	}
	return 0
}

func (x *CreateQuoteRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *CreateQuoteRequest) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *CreateQuoteRequest) GetDestinationRail() string {
	if x != nil {
		return x.DestinationRail
	}
	return ""
}

func (x *CreateQuoteRequest) GetUrgency() string {
	if x != nil {
		return x.Urgency
	}
	return ""
}

type QuoteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuoteId         string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BaseAmountMinor int64                  `protobuf:"varint,3,opt,name=base_amount_minor,json=baseAmountMinor,proto3" json:"base_amount_minor,omitempty"`
	BaseCurrency    string                 `protobuf:"bytes,4,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency   string                 `protobuf:"bytes,5,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	DestinationRail string                 `protobuf:"bytes,6,opt,name=destination_rail,json=destinationRail,proto3" json:"destination_rail,omitempty"`
	AmountOutMinor  int64                  `protobuf:"varint,7,opt,name=amount_out_minor,json=amountOutMinor,proto3" json:"amount_out_minor,omitempty"`
	RateMinor       int64                  `protobuf:"varint,8,opt,name=rate_minor,json=rateMinor,proto3" json:"rate_minor,omitempty"`
	FeeMinor        int64                  `protobuf:"varint,9,opt,name=fee_minor,json=feeMinor,proto3" json:"fee_minor,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TradeId         string                 `protobuf:"bytes,12,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_osai_quote_v1_quote_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteResponse) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *QuoteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QuoteResponse) GetBaseAmountMinor() int64 {
	if x != nil {
		return x.BaseAmountMinor
	}
	return 0
}

func (x *QuoteResponse) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *QuoteResponse) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *QuoteResponse) GetDestinationRail() string {
	if x != nil {
		return x.DestinationRail
	}
	return ""
}

func (x *QuoteResponse) GetAmountOutMinor() int64 {
	if x != nil {
		return x.AmountOutMinor
	}
	return 0
}

func (x *QuoteResponse) GetRateMinor() int64 {
	if x != nil {
		return x.RateMinor
	}
	return 0
}

func (x *QuoteResponse) GetFeeMinor() int64 {
	if x != nil {
		return x.FeeMinor
	}
	return 0
}

func (x *QuoteResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *QuoteResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *QuoteResponse) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	QuoteId       string                 `protobuf:"bytes,2,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_quote_v1_quote_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuoteRequest) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *GetQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *GetQuoteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type AcceptQuoteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId  string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	QuoteId        string                 `protobuf:"bytes,2,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptQuoteRequest) Reset() {
	*x = AcceptQuoteRequest{}
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptQuoteRequest) ProtoMessage() {}

func (x *AcceptQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_quote_v1_quote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptQuoteRequest.ProtoReflect.Descriptor instead.
func (*AcceptQuoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_quote_v1_quote_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptQuoteRequest) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *AcceptQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *AcceptQuoteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *AcceptQuoteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_proto_osai_quote_v1_quote_proto protoreflect.FileDescriptor

const file_proto_osai_quote_v1_quote_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/osai/quote/v1/quote.proto\x12\rosai.quote.v1\"F\n" +
	"\x05Money\x12!\n" +
	"\famount_minor\x18\x01 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xc8\x02\n" +
	"\x12CreateQuoteRequest\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12*\n" +
	"\x11base_amount_minor\x18\x04 \x01(\x03R\x0fbaseAmountMinor\x12#\n" +
	"\rbase_currency\x18\x05 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\x06 \x01(\tR\rquoteCurrency\x12)\n" +
	"\x10destination_rail\x18\a \x01(\tR\x0fdestinationRail\x12\x18\n" +
	"\aurgency\x18\b \x01(\tR\aurgency\"\xac\x03\n" +
	"\rQuoteResponse\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12*\n" +
	"\x11base_amount_minor\x18\x03 \x01(\x03R\x0fbaseAmountMinor\x12#\n" +
	"\rbase_currency\x18\x04 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\x05 \x01(\tR\rquoteCurrency\x12)\n" +
	"\x10destination_rail\x18\x06 \x01(\tR\x0fdestinationRail\x12(\n" +
	"\x10amount_out_minor\x18\a \x01(\x03R\x0eamountOutMinor\x12\x1d\n" +
	"\n" +
	"rate_minor\x18\b \x01(\x03R\trateMinor\x12\x1b\n" +
	"\tfee_minor\x18\t \x01(\x03R\bfeeMinor\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tR\texpiresAt\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrade_id\x18\f \x01(\tR\atradeId\"z\n" +
	"\x0fGetQuoteRequest\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12\x19\n" +
	"\bquote_id\x18\x02 \x01(\tR\aquoteId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\xa6\x01\n" +
	"\x12AcceptQuoteRequest\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12\x19\n" +
	"\bquote_id\x18\x02 \x01(\tR\aquoteId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId2\xf8\x01\n" +
	"\fQuoteService\x12N\n" +
	"\vCreateQuote\x12!.osai.quote.v1.CreateQuoteRequest\x1a\x1c.osai.quote.v1.QuoteResponse\x12H\n" +
	"\bGetQuote\x12\x1e.osai.quote.v1.GetQuoteRequest\x1a\x1c.osai.quote.v1.QuoteResponse\x12N\n" +
	"\vAcceptQuote\x12!.osai.quote.v1.AcceptQuoteRequest\x1a\x1c.osai.quote.v1.QuoteResponseB2Z0github.com/osai/osai/proto/osai/quote/v1;quotev1b\x06proto3"

var (
	file_proto_osai_quote_v1_quote_proto_rawDescOnce sync.Once
	file_proto_osai_quote_v1_quote_proto_rawDescData []byte
)

func file_proto_osai_quote_v1_quote_proto_rawDescGZIP() []byte {
	file_proto_osai_quote_v1_quote_proto_rawDescOnce.Do(func() {
		file_proto_osai_quote_v1_quote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_osai_quote_v1_quote_proto_rawDesc), len(file_proto_osai_quote_v1_quote_proto_rawDesc)))
	})
	return file_proto_osai_quote_v1_quote_proto_rawDescData
}

var file_proto_osai_quote_v1_quote_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_osai_quote_v1_quote_proto_goTypes = []any{
	(*Money)(nil),              // 0: osai.quote.v1.Money
	(*CreateQuoteRequest)(nil), // 1: osai.quote.v1.CreateQuoteRequest
	(*QuoteResponse)(nil),      // 2: osai.quote.v1.QuoteResponse
	(*GetQuoteRequest)(nil),    // 3: osai.quote.v1.GetQuoteRequest
	(*AcceptQuoteRequest)(nil), // 4: osai.quote.v1.AcceptQuoteRequest
}
var file_proto_osai_quote_v1_quote_proto_depIdxs = []int32{
	1, // 0: osai.quote.v1.QuoteService.CreateQuote:input_type -> osai.quote.v1.CreateQuoteRequest
	3, // 1: osai.quote.v1.QuoteService.GetQuote:input_type -> osai.quote.v1.GetQuoteRequest
	4, // 2: osai.quote.v1.QuoteService.AcceptQuote:input_type -> osai.quote.v1.AcceptQuoteRequest
	2, // 3: osai.quote.v1.QuoteService.CreateQuote:output_type -> osai.quote.v1.QuoteResponse
	2, // 4: osai.quote.v1.QuoteService.GetQuote:output_type -> osai.quote.v1.QuoteResponse
	2, // 5: osai.quote.v1.QuoteService.AcceptQuote:output_type -> osai.quote.v1.QuoteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_osai_quote_v1_quote_proto_init() }
func file_proto_osai_quote_v1_quote_proto_init() {
	if File_proto_osai_quote_v1_quote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_osai_quote_v1_quote_proto_rawDesc), len(file_proto_osai_quote_v1_quote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_osai_quote_v1_quote_proto_goTypes,
		DependencyIndexes: file_proto_osai_quote_v1_quote_proto_depIdxs,
		MessageInfos:      file_proto_osai_quote_v1_quote_proto_msgTypes,
	}.Build()
	File_proto_osai_quote_v1_quote_proto = out.File
	file_proto_osai_quote_v1_quote_proto_goTypes = nil
	file_proto_osai_quote_v1_quote_proto_depIdxs = nil
}
