// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: proto/osai/settlement/v1/settlement.proto

package settlementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettlementService_CreateSettlementForTrade_FullMethodName = "/osai.settlement.v1.SettlementService/CreateSettlementForTrade"
	SettlementService_GetSettlement_FullMethodName            = "/osai.settlement.v1.SettlementService/GetSettlement"
	SettlementService_ListConfirmedSettlements_FullMethodName = "/osai.settlement.v1.SettlementService/ListConfirmedSettlements"
)

// SettlementServiceClient is the client API for SettlementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettlementServiceClient interface {
	CreateSettlementForTrade(ctx context.Context, in *CreateSettlementForTradeRequest, opts ...grpc.CallOption) (*SettlementResponse, error)
	GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error)
	ListConfirmedSettlements(ctx context.Context, in *ListConfirmedSettlementsRequest, opts ...grpc.CallOption) (*ListConfirmedSettlementsResponse, error)
}

type settlementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettlementServiceClient(cc grpc.ClientConnInterface) SettlementServiceClient {
	return &settlementServiceClient{cc}
}

func (c *settlementServiceClient) CreateSettlementForTrade(ctx context.Context, in *CreateSettlementForTradeRequest, opts ...grpc.CallOption) (*SettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementResponse)
	err := c.cc.Invoke(ctx, SettlementService_CreateSettlementForTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settlementServiceClient) GetSettlement(ctx context.Context, in *GetSettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementResponse)
	err := c.cc.Invoke(ctx, SettlementService_GetSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settlementServiceClient) ListConfirmedSettlements(ctx context.Context, in *ListConfirmedSettlementsRequest, opts ...grpc.CallOption) (*ListConfirmedSettlementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfirmedSettlementsResponse)
	err := c.cc.Invoke(ctx, SettlementService_ListConfirmedSettlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettlementServiceServer is the server API for SettlementService service.
// All implementations must embed UnimplementedSettlementServiceServer
// for forward compatibility.
type SettlementServiceServer interface {
	CreateSettlementForTrade(context.Context, *CreateSettlementForTradeRequest) (*SettlementResponse, error)
	GetSettlement(context.Context, *GetSettlementRequest) (*SettlementResponse, error)
	ListConfirmedSettlements(context.Context, *ListConfirmedSettlementsRequest) (*ListConfirmedSettlementsResponse, error)
	mustEmbedUnimplementedSettlementServiceServer()
}

// UnimplementedSettlementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettlementServiceServer struct{}

func (UnimplementedSettlementServiceServer) CreateSettlementForTrade(context.Context, *CreateSettlementForTradeRequest) (*SettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSettlementForTrade not implemented")
}
func (UnimplementedSettlementServiceServer) GetSettlement(context.Context, *GetSettlementRequest) (*SettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettlement not implemented")
}
func (UnimplementedSettlementServiceServer) ListConfirmedSettlements(context.Context, *ListConfirmedSettlementsRequest) (*ListConfirmedSettlementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfirmedSettlements not implemented")
}
func (UnimplementedSettlementServiceServer) mustEmbedUnimplementedSettlementServiceServer() {}
func (UnimplementedSettlementServiceServer) testEmbeddedByValue()                           {}

// UnsafeSettlementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettlementServiceServer will
// result in compilation errors.
type UnsafeSettlementServiceServer interface {
	mustEmbedUnimplementedSettlementServiceServer()
}

func RegisterSettlementServiceServer(s grpc.ServiceRegistrar, srv SettlementServiceServer) {
	// If the following call panics, it indicates UnimplementedSettlementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettlementService_ServiceDesc, srv)
}

func _SettlementService_CreateSettlementForTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSettlementForTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServiceServer).CreateSettlementForTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettlementService_CreateSettlementForTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServiceServer).CreateSettlementForTrade(ctx, req.(*CreateSettlementForTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettlementService_GetSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServiceServer).GetSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettlementService_GetSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServiceServer).GetSettlement(ctx, req.(*GetSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettlementService_ListConfirmedSettlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfirmedSettlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServiceServer).ListConfirmedSettlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettlementService_ListConfirmedSettlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServiceServer).ListConfirmedSettlements(ctx, req.(*ListConfirmedSettlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettlementService_ServiceDesc is the grpc.ServiceDesc for SettlementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettlementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osai.settlement.v1.SettlementService",
	HandlerType: (*SettlementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSettlementForTrade",
			Handler:    _SettlementService_CreateSettlementForTrade_Handler,
		},
		{
			MethodName: "GetSettlement",
			Handler:    _SettlementService_GetSettlement_Handler,
		},
		{
			MethodName: "ListConfirmedSettlements",
			Handler:    _SettlementService_ListConfirmedSettlements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/osai/settlement/v1/settlement.proto",
}
