// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/osai/trade/v1/trade.proto

package tradev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMinor   int64                  `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_osai_trade_v1_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_trade_v1_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_osai_trade_v1_trade_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateTradeFromAcceptedQuoteRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId        string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	QuoteId              string                 `protobuf:"bytes,2,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId        string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	BaseAmountMinor      int64                  `protobuf:"varint,5,opt,name=base_amount_minor,json=baseAmountMinor,proto3" json:"base_amount_minor,omitempty"`
	BaseCurrency         string                 `protobuf:"bytes,6,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency        string                 `protobuf:"bytes,7,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	Amount               *Money                 `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`
	BeneficiaryId        string                 `protobuf:"bytes,9,opt,name=beneficiary_id,json=beneficiaryId,proto3" json:"beneficiary_id,omitempty"`
	SettlementProviderId string                 `protobuf:"bytes,10,opt,name=settlement_provider_id,json=settlementProviderId,proto3" json:"settlement_provider_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateTradeFromAcceptedQuoteRequest) Reset() {
	*x = CreateTradeFromAcceptedQuoteRequest{}
	mi := &file_proto_osai_trade_v1_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTradeFromAcceptedQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeFromAcceptedQuoteRequest) ProtoMessage() {}

func (x *CreateTradeFromAcceptedQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_trade_v1_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeFromAcceptedQuoteRequest.ProtoReflect.Descriptor instead.
func (*CreateTradeFromAcceptedQuoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_trade_v1_trade_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetBaseAmountMinor() int64 {
	if x != nil {
		return x.BaseAmountMinor
	}
	return 0
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetBeneficiaryId() string {
	if x != nil {
		return x.BeneficiaryId
	}
	return ""
}

func (x *CreateTradeFromAcceptedQuoteRequest) GetSettlementProviderId() string {
	if x != nil {
		return x.SettlementProviderId
	}
	return ""
}

type TradeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TradeId              string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	InstitutionId        string                 `protobuf:"bytes,2,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	QuoteId              string                 `protobuf:"bytes,3,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	Status               string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	BaseAmountMinor      int64                  `protobuf:"varint,5,opt,name=base_amount_minor,json=baseAmountMinor,proto3" json:"base_amount_minor,omitempty"`
	BaseCurrency         string                 `protobuf:"bytes,6,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency        string                 `protobuf:"bytes,7,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	CorrelationId        string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SettlementId         string                 `protobuf:"bytes,9,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	BeneficiaryId        string                 `protobuf:"bytes,10,opt,name=beneficiary_id,json=beneficiaryId,proto3" json:"beneficiary_id,omitempty"`
	SettlementProviderId string                 `protobuf:"bytes,11,opt,name=settlement_provider_id,json=settlementProviderId,proto3" json:"settlement_provider_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	mi := &file_proto_osai_trade_v1_trade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_trade_v1_trade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_proto_osai_trade_v1_trade_proto_rawDescGZIP(), []int{2}
}

func (x *TradeResponse) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *TradeResponse) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *TradeResponse) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *TradeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TradeResponse) GetBaseAmountMinor() int64 {
	if x != nil {
		return x.BaseAmountMinor
	}
	return 0
}

func (x *TradeResponse) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *TradeResponse) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *TradeResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TradeResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *TradeResponse) GetBeneficiaryId() string {
	if x != nil {
		return x.BeneficiaryId
	}
	return ""
}

func (x *TradeResponse) GetSettlementProviderId() string {
	if x != nil {
		return x.SettlementProviderId
	}
	return ""
}

type GetTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	TradeId       string                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeRequest) Reset() {
	*x = GetTradeRequest{}
	mi := &file_proto_osai_trade_v1_trade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeRequest) ProtoMessage() {}

func (x *GetTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_trade_v1_trade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeRequest.ProtoReflect.Descriptor instead.
func (*GetTradeRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_trade_v1_trade_proto_rawDescGZIP(), []int{3}
}

func (x *GetTradeRequest) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *GetTradeRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *GetTradeRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_proto_osai_trade_v1_trade_proto protoreflect.FileDescriptor

const file_proto_osai_trade_v1_trade_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/osai/trade/v1/trade.proto\x12\rosai.trade.v1\"F\n" +
	"\x05Money\x12!\n" +
	"\famount_minor\x18\x01 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xba\x03\n" +
	"#CreateTradeFromAcceptedQuoteRequest\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12\x19\n" +
	"\bquote_id\x18\x02 \x01(\tR\aquoteId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12*\n" +
	"\x11base_amount_minor\x18\x05 \x01(\x03R\x0fbaseAmountMinor\x12#\n" +
	"\rbase_currency\x18\x06 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\a \x01(\tR\rquoteCurrency\x12,\n" +
	"\x06amount\x18\b \x01(\v2\x14.osai.trade.v1.MoneyR\x06amount\x12%\n" +
	"\x0ebeneficiary_id\x18\t \x01(\tR\rbeneficiaryId\x124\n" +
	"\x16settlement_provider_id\x18\n" +
	" \x01(\tR\x14settlementProviderId\"\xa5\x03\n" +
	"\rTradeResponse\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12%\n" +
	"\x0einstitution_id\x18\x02 \x01(\tR\rinstitutionId\x12\x19\n" +
	"\bquote_id\x18\x03 \x01(\tR\aquoteId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12*\n" +
	"\x11base_amount_minor\x18\x05 \x01(\x03R\x0fbaseAmountMinor\x12#\n" +
	"\rbase_currency\x18\x06 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\a \x01(\tR\rquoteCurrency\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12#\n" +
	"\rsettlement_id\x18\t \x01(\tR\fsettlementId\x12%\n" +
	"\x0ebeneficiary_id\x18\n" +
	" \x01(\tR\rbeneficiaryId\x124\n" +
	"\x16settlement_provider_id\x18\v \x01(\tR\x14settlementProviderId\"z\n" +
	"\x0fGetTradeRequest\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\tR\atradeId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId2\xca\x01\n" +
	"\fTradeService\x12p\n" +
	"\x1cCreateTradeFromAcceptedQuote\x122.osai.trade.v1.CreateTradeFromAcceptedQuoteRequest\x1a\x1c.osai.trade.v1.TradeResponse\x12H\n" +
	"\bGetTrade\x12\x1e.osai.trade.v1.GetTradeRequest\x1a\x1c.osai.trade.v1.TradeResponseB2Z0github.com/osai/osai/proto/osai/trade/v1;tradev1b\x06proto3"

var (
	file_proto_osai_trade_v1_trade_proto_rawDescOnce sync.Once
	file_proto_osai_trade_v1_trade_proto_rawDescData []byte
)

func file_proto_osai_trade_v1_trade_proto_rawDescGZIP() []byte {
	file_proto_osai_trade_v1_trade_proto_rawDescOnce.Do(func() {
		file_proto_osai_trade_v1_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_osai_trade_v1_trade_proto_rawDesc), len(file_proto_osai_trade_v1_trade_proto_rawDesc)))
	})
	return file_proto_osai_trade_v1_trade_proto_rawDescData
}

var file_proto_osai_trade_v1_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_osai_trade_v1_trade_proto_goTypes = []any{
	(*Money)(nil), // 0: osai.trade.v1.Money
	(*CreateTradeFromAcceptedQuoteRequest)(nil), // 1: osai.trade.v1.CreateTradeFromAcceptedQuoteRequest
	(*TradeResponse)(nil),                       // 2: osai.trade.v1.TradeResponse
	(*GetTradeRequest)(nil),                     // 3: osai.trade.v1.GetTradeRequest
}
var file_proto_osai_trade_v1_trade_proto_depIdxs = []int32{
	0, // 0: osai.trade.v1.CreateTradeFromAcceptedQuoteRequest.amount:type_name -> osai.trade.v1.Money
	1, // 1: osai.trade.v1.TradeService.CreateTradeFromAcceptedQuote:input_type -> osai.trade.v1.CreateTradeFromAcceptedQuoteRequest
	3, // 2: osai.trade.v1.TradeService.GetTrade:input_type -> osai.trade.v1.GetTradeRequest
	2, // 3: osai.trade.v1.TradeService.CreateTradeFromAcceptedQuote:output_type -> osai.trade.v1.TradeResponse
	2, // 4: osai.trade.v1.TradeService.GetTrade:output_type -> osai.trade.v1.TradeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_osai_trade_v1_trade_proto_init() }
func file_proto_osai_trade_v1_trade_proto_init() {
	if File_proto_osai_trade_v1_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_osai_trade_v1_trade_proto_rawDesc), len(file_proto_osai_trade_v1_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_osai_trade_v1_trade_proto_goTypes,
		DependencyIndexes: file_proto_osai_trade_v1_trade_proto_depIdxs,
		MessageInfos:      file_proto_osai_trade_v1_trade_proto_msgTypes,
	}.Build()
	File_proto_osai_trade_v1_trade_proto = out.File
	file_proto_osai_trade_v1_trade_proto_goTypes = nil
	file_proto_osai_trade_v1_trade_proto_depIdxs = nil
}
