// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: proto/osai/ledger/v1/ledger.proto

package ledgerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_ConfirmSettlement_FullMethodName            = "/osai.ledger.v1.LedgerService/ConfirmSettlement"
	LedgerService_FailSettlement_FullMethodName               = "/osai.ledger.v1.LedgerService/FailSettlement"
	LedgerService_ReverseSettlement_FullMethodName            = "/osai.ledger.v1.LedgerService/ReverseSettlement"
	LedgerService_PostReconciliationAdjustment_FullMethodName = "/osai.ledger.v1.LedgerService/PostReconciliationAdjustment"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	ConfirmSettlement(ctx context.Context, in *SettlementCommand, opts ...grpc.CallOption) (*SettlementCommandResponse, error)
	FailSettlement(ctx context.Context, in *SettlementCommand, opts ...grpc.CallOption) (*SettlementCommandResponse, error)
	ReverseSettlement(ctx context.Context, in *SettlementCommand, opts ...grpc.CallOption) (*SettlementCommandResponse, error)
	PostReconciliationAdjustment(ctx context.Context, in *ReconciliationAdjustmentCommand, opts ...grpc.CallOption) (*SettlementCommandResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) ConfirmSettlement(ctx context.Context, in *SettlementCommand, opts ...grpc.CallOption) (*SettlementCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementCommandResponse)
	err := c.cc.Invoke(ctx, LedgerService_ConfirmSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) FailSettlement(ctx context.Context, in *SettlementCommand, opts ...grpc.CallOption) (*SettlementCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementCommandResponse)
	err := c.cc.Invoke(ctx, LedgerService_FailSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReverseSettlement(ctx context.Context, in *SettlementCommand, opts ...grpc.CallOption) (*SettlementCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementCommandResponse)
	err := c.cc.Invoke(ctx, LedgerService_ReverseSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) PostReconciliationAdjustment(ctx context.Context, in *ReconciliationAdjustmentCommand, opts ...grpc.CallOption) (*SettlementCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementCommandResponse)
	err := c.cc.Invoke(ctx, LedgerService_PostReconciliationAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	ConfirmSettlement(context.Context, *SettlementCommand) (*SettlementCommandResponse, error)
	FailSettlement(context.Context, *SettlementCommand) (*SettlementCommandResponse, error)
	ReverseSettlement(context.Context, *SettlementCommand) (*SettlementCommandResponse, error)
	PostReconciliationAdjustment(context.Context, *ReconciliationAdjustmentCommand) (*SettlementCommandResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) ConfirmSettlement(context.Context, *SettlementCommand) (*SettlementCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmSettlement not implemented")
}
func (UnimplementedLedgerServiceServer) FailSettlement(context.Context, *SettlementCommand) (*SettlementCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailSettlement not implemented")
}
func (UnimplementedLedgerServiceServer) ReverseSettlement(context.Context, *SettlementCommand) (*SettlementCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseSettlement not implemented")
}
func (UnimplementedLedgerServiceServer) PostReconciliationAdjustment(context.Context, *ReconciliationAdjustmentCommand) (*SettlementCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostReconciliationAdjustment not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_ConfirmSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettlementCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ConfirmSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ConfirmSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ConfirmSettlement(ctx, req.(*SettlementCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_FailSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettlementCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).FailSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_FailSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).FailSettlement(ctx, req.(*SettlementCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReverseSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettlementCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReverseSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReverseSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReverseSettlement(ctx, req.(*SettlementCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_PostReconciliationAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconciliationAdjustmentCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).PostReconciliationAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_PostReconciliationAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).PostReconciliationAdjustment(ctx, req.(*ReconciliationAdjustmentCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osai.ledger.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmSettlement",
			Handler:    _LedgerService_ConfirmSettlement_Handler,
		},
		{
			MethodName: "FailSettlement",
			Handler:    _LedgerService_FailSettlement_Handler,
		},
		{
			MethodName: "ReverseSettlement",
			Handler:    _LedgerService_ReverseSettlement_Handler,
		},
		{
			MethodName: "PostReconciliationAdjustment",
			Handler:    _LedgerService_PostReconciliationAdjustment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/osai/ledger/v1/ledger.proto",
}
