// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: osai/ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMinor   int64                  `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_osai_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type SettlementCommand struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey          string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId           string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SettlementInstructionId string                 `protobuf:"bytes,3,opt,name=settlement_instruction_id,json=settlementInstructionId,proto3" json:"settlement_instruction_id,omitempty"`
	TradeId                 string                 `protobuf:"bytes,4,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	ObligationId            string                 `protobuf:"bytes,5,opt,name=obligation_id,json=obligationId,proto3" json:"obligation_id,omitempty"`
	ProviderReference       string                 `protobuf:"bytes,6,opt,name=provider_reference,json=providerReference,proto3" json:"provider_reference,omitempty"`
	ExternalReference       string                 `protobuf:"bytes,7,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	Beneficiary             string                 `protobuf:"bytes,8,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	Amount                  *Money                 `protobuf:"bytes,9,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose                 string                 `protobuf:"bytes,10,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SettlementCommand) Reset() {
	*x = SettlementCommand{}
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementCommand) ProtoMessage() {}

func (x *SettlementCommand) ProtoReflect() protoreflect.Message {
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementCommand.ProtoReflect.Descriptor instead.
func (*SettlementCommand) Descriptor() ([]byte, []int) {
	return file_osai_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *SettlementCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SettlementCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *SettlementCommand) GetSettlementInstructionId() string {
	if x != nil {
		return x.SettlementInstructionId
	}
	return ""
}

func (x *SettlementCommand) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *SettlementCommand) GetObligationId() string {
	if x != nil {
		return x.ObligationId
	}
	return ""
}

func (x *SettlementCommand) GetProviderReference() string {
	if x != nil {
		return x.ProviderReference
	}
	return ""
}

func (x *SettlementCommand) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *SettlementCommand) GetBeneficiary() string {
	if x != nil {
		return x.Beneficiary
	}
	return ""
}

func (x *SettlementCommand) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *SettlementCommand) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type LedgerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerError) Reset() {
	*x = LedgerError{}
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerError) ProtoMessage() {}

func (x *LedgerError) ProtoReflect() protoreflect.Message {
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerError.ProtoReflect.Descriptor instead.
func (*LedgerError) Descriptor() ([]byte, []int) {
	return file_osai_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *LedgerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LedgerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SettlementCommandResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JournalId      string                 `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
	AlreadyApplied bool                   `protobuf:"varint,2,opt,name=already_applied,json=alreadyApplied,proto3" json:"already_applied,omitempty"`
	Error          *LedgerError           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SettlementCommandResponse) Reset() {
	*x = SettlementCommandResponse{}
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementCommandResponse) ProtoMessage() {}

func (x *SettlementCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementCommandResponse.ProtoReflect.Descriptor instead.
func (*SettlementCommandResponse) Descriptor() ([]byte, []int) {
	return file_osai_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *SettlementCommandResponse) GetJournalId() string {
	if x != nil {
		return x.JournalId
	}
	return ""
}

func (x *SettlementCommandResponse) GetAlreadyApplied() bool {
	if x != nil {
		return x.AlreadyApplied
	}
	return false
}

func (x *SettlementCommandResponse) GetError() *LedgerError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReconciliationAdjustmentCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	BreakId        string                 `protobuf:"bytes,3,opt,name=break_id,json=breakId,proto3" json:"break_id,omitempty"`
	Maker          string                 `protobuf:"bytes,4,opt,name=maker,proto3" json:"maker,omitempty"`
	Checker        string                 `protobuf:"bytes,5,opt,name=checker,proto3" json:"checker,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	AmountMinor    int64                  `protobuf:"varint,7,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Reason         string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	JournalTag     string                 `protobuf:"bytes,9,opt,name=journal_tag,json=journalTag,proto3" json:"journal_tag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReconciliationAdjustmentCommand) Reset() {
	*x = ReconciliationAdjustmentCommand{}
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationAdjustmentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationAdjustmentCommand) ProtoMessage() {}

func (x *ReconciliationAdjustmentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_osai_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationAdjustmentCommand.ProtoReflect.Descriptor instead.
func (*ReconciliationAdjustmentCommand) Descriptor() ([]byte, []int) {
	return file_osai_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *ReconciliationAdjustmentCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReconciliationAdjustmentCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ReconciliationAdjustmentCommand) GetBreakId() string {
	if x != nil {
		return x.BreakId
	}
	return ""
}

func (x *ReconciliationAdjustmentCommand) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *ReconciliationAdjustmentCommand) GetChecker() string {
	if x != nil {
		return x.Checker
	}
	return ""
}

func (x *ReconciliationAdjustmentCommand) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ReconciliationAdjustmentCommand) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *ReconciliationAdjustmentCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReconciliationAdjustmentCommand) GetJournalTag() string {
	if x != nil {
		return x.JournalTag
	}
	return ""
}

var File_osai_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_osai_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1bosai/ledger/v1/ledger.proto\x12\x0eosai.ledger.v1\"F\n" +
	"\x05Money\x12!\n" +
	"\famount_minor\x18\x01 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xa8\x03\n" +
	"\x11SettlementCommand\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12:\n" +
	"\x19settlement_instruction_id\x18\x03 \x01(\tR\x17settlementInstructionId\x12\x19\n" +
	"\btrade_id\x18\x04 \x01(\tR\atradeId\x12#\n" +
	"\robligation_id\x18\x05 \x01(\tR\fobligationId\x12-\n" +
	"\x12provider_reference\x18\x06 \x01(\tR\x11providerReference\x12-\n" +
	"\x12external_reference\x18\a \x01(\tR\x11externalReference\x12 \n" +
	"\vbeneficiary\x18\b \x01(\tR\vbeneficiary\x12-\n" +
	"\x06amount\x18\t \x01(\v2\x15.osai.ledger.v1.MoneyR\x06amount\x12\x18\n" +
	"\apurpose\x18\n" +
	" \x01(\tR\apurpose\";\n" +
	"\vLedgerError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x01\n" +
	"\x19SettlementCommandResponse\x12\x1d\n" +
	"\n" +
	"journal_id\x18\x01 \x01(\tR\tjournalId\x12'\n" +
	"\x0falready_applied\x18\x02 \x01(\bR\x0ealreadyApplied\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.osai.ledger.v1.LedgerErrorR\x05error\"\xb4\x02\n" +
	"\x1fReconciliationAdjustmentCommand\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\bbreak_id\x18\x03 \x01(\tR\abreakId\x12\x14\n" +
	"\x05maker\x18\x04 \x01(\tR\x05maker\x12\x18\n" +
	"\achecker\x18\x05 \x01(\tR\achecker\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\famount_minor\x18\a \x01(\x03R\vamountMinor\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1f\n" +
	"\vjournal_tag\x18\t \x01(\tR\n" +
	"journalTag2\xb1\x03\n" +
	"\rLedgerService\x12a\n" +
	"\x11ConfirmSettlement\x12!.osai.ledger.v1.SettlementCommand\x1a).osai.ledger.v1.SettlementCommandResponse\x12^\n" +
	"\x0eFailSettlement\x12!.osai.ledger.v1.SettlementCommand\x1a).osai.ledger.v1.SettlementCommandResponse\x12a\n" +
	"\x11ReverseSettlement\x12!.osai.ledger.v1.SettlementCommand\x1a).osai.ledger.v1.SettlementCommandResponse\x12z\n" +
	"\x1cPostReconciliationAdjustment\x12/.osai.ledger.v1.ReconciliationAdjustmentCommand\x1a).osai.ledger.v1.SettlementCommandResponseB4Z2github.com/osai/osai/proto/osai/ledger/v1;ledgerv1b\x06proto3"

var (
	file_osai_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_osai_ledger_v1_ledger_proto_rawDescData []byte
)

func file_osai_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_osai_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_osai_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osai_ledger_v1_ledger_proto_rawDesc), len(file_osai_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_osai_ledger_v1_ledger_proto_rawDescData
}

var file_osai_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_osai_ledger_v1_ledger_proto_goTypes = []any{
	(*Money)(nil),                           // 0: osai.ledger.v1.Money
	(*SettlementCommand)(nil),               // 1: osai.ledger.v1.SettlementCommand
	(*LedgerError)(nil),                     // 2: osai.ledger.v1.LedgerError
	(*SettlementCommandResponse)(nil),       // 3: osai.ledger.v1.SettlementCommandResponse
	(*ReconciliationAdjustmentCommand)(nil), // 4: osai.ledger.v1.ReconciliationAdjustmentCommand
}
var file_osai_ledger_v1_ledger_proto_depIdxs = []int32{
	0, // 0: osai.ledger.v1.SettlementCommand.amount:type_name -> osai.ledger.v1.Money
	2, // 1: osai.ledger.v1.SettlementCommandResponse.error:type_name -> osai.ledger.v1.LedgerError
	1, // 2: osai.ledger.v1.LedgerService.ConfirmSettlement:input_type -> osai.ledger.v1.SettlementCommand
	1, // 3: osai.ledger.v1.LedgerService.FailSettlement:input_type -> osai.ledger.v1.SettlementCommand
	1, // 4: osai.ledger.v1.LedgerService.ReverseSettlement:input_type -> osai.ledger.v1.SettlementCommand
	4, // 5: osai.ledger.v1.LedgerService.PostReconciliationAdjustment:input_type -> osai.ledger.v1.ReconciliationAdjustmentCommand
	3, // 6: osai.ledger.v1.LedgerService.ConfirmSettlement:output_type -> osai.ledger.v1.SettlementCommandResponse
	3, // 7: osai.ledger.v1.LedgerService.FailSettlement:output_type -> osai.ledger.v1.SettlementCommandResponse
	3, // 8: osai.ledger.v1.LedgerService.ReverseSettlement:output_type -> osai.ledger.v1.SettlementCommandResponse
	3, // 9: osai.ledger.v1.LedgerService.PostReconciliationAdjustment:output_type -> osai.ledger.v1.SettlementCommandResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_osai_ledger_v1_ledger_proto_init() }
func file_osai_ledger_v1_ledger_proto_init() {
	if File_osai_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osai_ledger_v1_ledger_proto_rawDesc), len(file_osai_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osai_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_osai_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_osai_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_osai_ledger_v1_ledger_proto = out.File
	file_osai_ledger_v1_ledger_proto_goTypes = nil
	file_osai_ledger_v1_ledger_proto_depIdxs = nil
}
