// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/osai/customer/v1/customer.proto

package customerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialAuthRequest) Reset() {
	*x = CredentialAuthRequest{}
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialAuthRequest) ProtoMessage() {}

func (x *CredentialAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialAuthRequest.ProtoReflect.Descriptor instead.
func (*CredentialAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_customer_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialAuthRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *CredentialAuthRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type InstitutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstitutionRequest) Reset() {
	*x = InstitutionRequest{}
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstitutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstitutionRequest) ProtoMessage() {}

func (x *InstitutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstitutionRequest.ProtoReflect.Descriptor instead.
func (*InstitutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_osai_customer_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *InstitutionRequest) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

type AuthContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId     string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	InstitutionStatus string                 `protobuf:"bytes,2,opt,name=institution_status,json=institutionStatus,proto3" json:"institution_status,omitempty"`
	KybStatus         string                 `protobuf:"bytes,3,opt,name=kyb_status,json=kybStatus,proto3" json:"kyb_status,omitempty"`
	ApiAccessStatus   string                 `protobuf:"bytes,4,opt,name=api_access_status,json=apiAccessStatus,proto3" json:"api_access_status,omitempty"`
	ApiEnabled        bool                   `protobuf:"varint,5,opt,name=api_enabled,json=apiEnabled,proto3" json:"api_enabled,omitempty"`
	Entitlements      []string               `protobuf:"bytes,6,rep,name=entitlements,proto3" json:"entitlements,omitempty"`
	RequestId         string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthContext) Reset() {
	*x = AuthContext{}
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthContext) ProtoMessage() {}

func (x *AuthContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthContext.ProtoReflect.Descriptor instead.
func (*AuthContext) Descriptor() ([]byte, []int) {
	return file_proto_osai_customer_v1_customer_proto_rawDescGZIP(), []int{2}
}

func (x *AuthContext) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *AuthContext) GetInstitutionStatus() string {
	if x != nil {
		return x.InstitutionStatus
	}
	return ""
}

func (x *AuthContext) GetKybStatus() string {
	if x != nil {
		return x.KybStatus
	}
	return ""
}

func (x *AuthContext) GetApiAccessStatus() string {
	if x != nil {
		return x.ApiAccessStatus
	}
	return ""
}

func (x *AuthContext) GetApiEnabled() bool {
	if x != nil {
		return x.ApiEnabled
	}
	return false
}

func (x *AuthContext) GetEntitlements() []string {
	if x != nil {
		return x.Entitlements
	}
	return nil
}

func (x *AuthContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Institution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	KybStatus     string                 `protobuf:"bytes,4,opt,name=kyb_status,json=kybStatus,proto3" json:"kyb_status,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	ApiEnabled    bool                   `protobuf:"varint,6,opt,name=api_enabled,json=apiEnabled,proto3" json:"api_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Institution) Reset() {
	*x = Institution{}
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Institution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Institution) ProtoMessage() {}

func (x *Institution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Institution.ProtoReflect.Descriptor instead.
func (*Institution) Descriptor() ([]byte, []int) {
	return file_proto_osai_customer_v1_customer_proto_rawDescGZIP(), []int{3}
}

func (x *Institution) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *Institution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Institution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Institution) GetKybStatus() string {
	if x != nil {
		return x.KybStatus
	}
	return ""
}

func (x *Institution) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Institution) GetApiEnabled() bool {
	if x != nil {
		return x.ApiEnabled
	}
	return false
}

type WebhookConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId string                 `protobuf:"bytes,1,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,2,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookConfiguration) Reset() {
	*x = WebhookConfiguration{}
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookConfiguration) ProtoMessage() {}

func (x *WebhookConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_osai_customer_v1_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookConfiguration.ProtoReflect.Descriptor instead.
func (*WebhookConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_osai_customer_v1_customer_proto_rawDescGZIP(), []int{4}
}

func (x *WebhookConfiguration) GetInstitutionId() string {
	if x != nil {
		return x.InstitutionId
	}
	return ""
}

func (x *WebhookConfiguration) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *WebhookConfiguration) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *WebhookConfiguration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WebhookConfiguration) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_osai_customer_v1_customer_proto protoreflect.FileDescriptor

const file_proto_osai_customer_v1_customer_proto_rawDesc = "" +
	"\n" +
	"%proto/osai/customer/v1/customer.proto\x12\x10osai.customer.v1\"L\n" +
	"\x15CredentialAuthRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\";\n" +
	"\x12InstitutionRequest\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\"\x92\x02\n" +
	"\vAuthContext\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12-\n" +
	"\x12institution_status\x18\x02 \x01(\tR\x11institutionStatus\x12\x1d\n" +
	"\n" +
	"kyb_status\x18\x03 \x01(\tR\tkybStatus\x12*\n" +
	"\x11api_access_status\x18\x04 \x01(\tR\x0fapiAccessStatus\x12\x1f\n" +
	"\vapi_enabled\x18\x05 \x01(\bR\n" +
	"apiEnabled\x12\"\n" +
	"\fentitlements\x18\x06 \x03(\tR\fentitlements\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\xba\x01\n" +
	"\vInstitution\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"kyb_status\x18\x04 \x01(\tR\tkybStatus\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1f\n" +
	"\vapi_enabled\x18\x06 \x01(\bR\n" +
	"apiEnabled\"\xa8\x01\n" +
	"\x14WebhookConfiguration\x12%\n" +
	"\x0einstitution_id\x18\x01 \x01(\tR\rinstitutionId\x12\x1f\n" +
	"\vwebhook_url\x18\x02 \x01(\tR\n" +
	"webhookUrl\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\x8f\x03\n" +
	"\x0fCustomerService\x12_\n" +
	"\x15AuthenticateAPIClient\x12'.osai.customer.v1.CredentialAuthRequest\x1a\x1d.osai.customer.v1.AuthContext\x12[\n" +
	"\x14GetInstitutionAccess\x12$.osai.customer.v1.InstitutionRequest\x1a\x1d.osai.customer.v1.AuthContext\x12U\n" +
	"\x0eGetInstitution\x12$.osai.customer.v1.InstitutionRequest\x1a\x1d.osai.customer.v1.Institution\x12g\n" +
	"\x17GetWebhookConfiguration\x12$.osai.customer.v1.InstitutionRequest\x1a&.osai.customer.v1.WebhookConfigurationB8Z6github.com/osai/osai/proto/osai/customer/v1;customerv1b\x06proto3"

var (
	file_proto_osai_customer_v1_customer_proto_rawDescOnce sync.Once
	file_proto_osai_customer_v1_customer_proto_rawDescData []byte
)

func file_proto_osai_customer_v1_customer_proto_rawDescGZIP() []byte {
	file_proto_osai_customer_v1_customer_proto_rawDescOnce.Do(func() {
		file_proto_osai_customer_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_osai_customer_v1_customer_proto_rawDesc), len(file_proto_osai_customer_v1_customer_proto_rawDesc)))
	})
	return file_proto_osai_customer_v1_customer_proto_rawDescData
}

var file_proto_osai_customer_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_osai_customer_v1_customer_proto_goTypes = []any{
	(*CredentialAuthRequest)(nil), // 0: osai.customer.v1.CredentialAuthRequest
	(*InstitutionRequest)(nil),    // 1: osai.customer.v1.InstitutionRequest
	(*AuthContext)(nil),           // 2: osai.customer.v1.AuthContext
	(*Institution)(nil),           // 3: osai.customer.v1.Institution
	(*WebhookConfiguration)(nil),  // 4: osai.customer.v1.WebhookConfiguration
}
var file_proto_osai_customer_v1_customer_proto_depIdxs = []int32{
	0, // 0: osai.customer.v1.CustomerService.AuthenticateAPIClient:input_type -> osai.customer.v1.CredentialAuthRequest
	1, // 1: osai.customer.v1.CustomerService.GetInstitutionAccess:input_type -> osai.customer.v1.InstitutionRequest
	1, // 2: osai.customer.v1.CustomerService.GetInstitution:input_type -> osai.customer.v1.InstitutionRequest
	1, // 3: osai.customer.v1.CustomerService.GetWebhookConfiguration:input_type -> osai.customer.v1.InstitutionRequest
	2, // 4: osai.customer.v1.CustomerService.AuthenticateAPIClient:output_type -> osai.customer.v1.AuthContext
	2, // 5: osai.customer.v1.CustomerService.GetInstitutionAccess:output_type -> osai.customer.v1.AuthContext
	3, // 6: osai.customer.v1.CustomerService.GetInstitution:output_type -> osai.customer.v1.Institution
	4, // 7: osai.customer.v1.CustomerService.GetWebhookConfiguration:output_type -> osai.customer.v1.WebhookConfiguration
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_osai_customer_v1_customer_proto_init() }
func file_proto_osai_customer_v1_customer_proto_init() {
	if File_proto_osai_customer_v1_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_osai_customer_v1_customer_proto_rawDesc), len(file_proto_osai_customer_v1_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_osai_customer_v1_customer_proto_goTypes,
		DependencyIndexes: file_proto_osai_customer_v1_customer_proto_depIdxs,
		MessageInfos:      file_proto_osai_customer_v1_customer_proto_msgTypes,
	}.Build()
	File_proto_osai_customer_v1_customer_proto = out.File
	file_proto_osai_customer_v1_customer_proto_goTypes = nil
	file_proto_osai_customer_v1_customer_proto_depIdxs = nil
}
