// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: proto/osai/customer/v1/customer.proto

package customerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerService_AuthenticateAPIClient_FullMethodName   = "/osai.customer.v1.CustomerService/AuthenticateAPIClient"
	CustomerService_GetInstitutionAccess_FullMethodName    = "/osai.customer.v1.CustomerService/GetInstitutionAccess"
	CustomerService_GetInstitution_FullMethodName          = "/osai.customer.v1.CustomerService/GetInstitution"
	CustomerService_GetWebhookConfiguration_FullMethodName = "/osai.customer.v1.CustomerService/GetWebhookConfiguration"
	CustomerService_GetApprovedBeneficiary_FullMethodName  = "/osai.customer.v1.CustomerService/GetApprovedBeneficiary"
	CustomerService_RegisterBeneficiary_FullMethodName     = "/osai.customer.v1.CustomerService/RegisterBeneficiary"
)

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerServiceClient interface {
	AuthenticateAPIClient(ctx context.Context, in *CredentialAuthRequest, opts ...grpc.CallOption) (*AuthContext, error)
	GetInstitutionAccess(ctx context.Context, in *InstitutionRequest, opts ...grpc.CallOption) (*AuthContext, error)
	GetInstitution(ctx context.Context, in *InstitutionRequest, opts ...grpc.CallOption) (*Institution, error)
	GetWebhookConfiguration(ctx context.Context, in *InstitutionRequest, opts ...grpc.CallOption) (*WebhookConfiguration, error)
	GetApprovedBeneficiary(ctx context.Context, in *BeneficiaryRequest, opts ...grpc.CallOption) (*Beneficiary, error)
	RegisterBeneficiary(ctx context.Context, in *RegisterBeneficiaryRequest, opts ...grpc.CallOption) (*Beneficiary, error)
}

type customerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerServiceClient(cc grpc.ClientConnInterface) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) AuthenticateAPIClient(ctx context.Context, in *CredentialAuthRequest, opts ...grpc.CallOption) (*AuthContext, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthContext)
	err := c.cc.Invoke(ctx, CustomerService_AuthenticateAPIClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetInstitutionAccess(ctx context.Context, in *InstitutionRequest, opts ...grpc.CallOption) (*AuthContext, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthContext)
	err := c.cc.Invoke(ctx, CustomerService_GetInstitutionAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetInstitution(ctx context.Context, in *InstitutionRequest, opts ...grpc.CallOption) (*Institution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Institution)
	err := c.cc.Invoke(ctx, CustomerService_GetInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetWebhookConfiguration(ctx context.Context, in *InstitutionRequest, opts ...grpc.CallOption) (*WebhookConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookConfiguration)
	err := c.cc.Invoke(ctx, CustomerService_GetWebhookConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetApprovedBeneficiary(ctx context.Context, in *BeneficiaryRequest, opts ...grpc.CallOption) (*Beneficiary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Beneficiary)
	err := c.cc.Invoke(ctx, CustomerService_GetApprovedBeneficiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) RegisterBeneficiary(ctx context.Context, in *RegisterBeneficiaryRequest, opts ...grpc.CallOption) (*Beneficiary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Beneficiary)
	err := c.cc.Invoke(ctx, CustomerService_RegisterBeneficiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
// All implementations must embed UnimplementedCustomerServiceServer
// for forward compatibility.
type CustomerServiceServer interface {
	AuthenticateAPIClient(context.Context, *CredentialAuthRequest) (*AuthContext, error)
	GetInstitutionAccess(context.Context, *InstitutionRequest) (*AuthContext, error)
	GetInstitution(context.Context, *InstitutionRequest) (*Institution, error)
	GetWebhookConfiguration(context.Context, *InstitutionRequest) (*WebhookConfiguration, error)
	GetApprovedBeneficiary(context.Context, *BeneficiaryRequest) (*Beneficiary, error)
	RegisterBeneficiary(context.Context, *RegisterBeneficiaryRequest) (*Beneficiary, error)
	mustEmbedUnimplementedCustomerServiceServer()
}

// UnimplementedCustomerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerServiceServer struct{}

func (UnimplementedCustomerServiceServer) AuthenticateAPIClient(context.Context, *CredentialAuthRequest) (*AuthContext, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateAPIClient not implemented")
}
func (UnimplementedCustomerServiceServer) GetInstitutionAccess(context.Context, *InstitutionRequest) (*AuthContext, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstitutionAccess not implemented")
}
func (UnimplementedCustomerServiceServer) GetInstitution(context.Context, *InstitutionRequest) (*Institution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstitution not implemented")
}
func (UnimplementedCustomerServiceServer) GetWebhookConfiguration(context.Context, *InstitutionRequest) (*WebhookConfiguration, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhookConfiguration not implemented")
}
func (UnimplementedCustomerServiceServer) GetApprovedBeneficiary(context.Context, *BeneficiaryRequest) (*Beneficiary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApprovedBeneficiary not implemented")
}
func (UnimplementedCustomerServiceServer) RegisterBeneficiary(context.Context, *RegisterBeneficiaryRequest) (*Beneficiary, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBeneficiary not implemented")
}
func (UnimplementedCustomerServiceServer) mustEmbedUnimplementedCustomerServiceServer() {}
func (UnimplementedCustomerServiceServer) testEmbeddedByValue()                         {}

// UnsafeCustomerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServiceServer will
// result in compilation errors.
type UnsafeCustomerServiceServer interface {
	mustEmbedUnimplementedCustomerServiceServer()
}

func RegisterCustomerServiceServer(s grpc.ServiceRegistrar, srv CustomerServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerService_ServiceDesc, srv)
}

func _CustomerService_AuthenticateAPIClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).AuthenticateAPIClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_AuthenticateAPIClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).AuthenticateAPIClient(ctx, req.(*CredentialAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetInstitutionAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetInstitutionAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetInstitutionAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetInstitutionAccess(ctx, req.(*InstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetInstitution(ctx, req.(*InstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetWebhookConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetWebhookConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetWebhookConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetWebhookConfiguration(ctx, req.(*InstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetApprovedBeneficiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeneficiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetApprovedBeneficiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetApprovedBeneficiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetApprovedBeneficiary(ctx, req.(*BeneficiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_RegisterBeneficiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBeneficiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).RegisterBeneficiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_RegisterBeneficiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).RegisterBeneficiary(ctx, req.(*RegisterBeneficiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerService_ServiceDesc is the grpc.ServiceDesc for CustomerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osai.customer.v1.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateAPIClient",
			Handler:    _CustomerService_AuthenticateAPIClient_Handler,
		},
		{
			MethodName: "GetInstitutionAccess",
			Handler:    _CustomerService_GetInstitutionAccess_Handler,
		},
		{
			MethodName: "GetInstitution",
			Handler:    _CustomerService_GetInstitution_Handler,
		},
		{
			MethodName: "GetWebhookConfiguration",
			Handler:    _CustomerService_GetWebhookConfiguration_Handler,
		},
		{
			MethodName: "GetApprovedBeneficiary",
			Handler:    _CustomerService_GetApprovedBeneficiary_Handler,
		},
		{
			MethodName: "RegisterBeneficiary",
			Handler:    _CustomerService_RegisterBeneficiary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/osai/customer/v1/customer.proto",
}
